@extends('templates.default')

@section('content')
        @include('templates.partials.preloader')
        @include('templates.partials.header')
        @include('templates.partials.navigation')
        @include('templates.partials.about')
        @include('templates.partials.getstarted')
        @include('templates.partials.buying')
        @include('templates.partials.carousel')
        @include('templates.partials.subscribe')
        @include('templates.partials.teams')
        @include('templates.partials.feedback')
        @include('templates.partials.footer')
@stop
